name: Caller

on:
  workflow_dispatch:
    inputs:
      boolean:
        description: 'Boolean'
        required: false
        default: false
        type: boolean
      string:
        description: 'String'
        required: false
        type: string
        default: 'string'
      number:
        description: 'Number'
        required: false
        type: string
        default: '1'
jobs:
  test:
    uses: ./.github/workflows/execution.yml
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      boolean1: false
      string1: ${{github.event.inputs.string}}
      number1:  ${{github.event.inputs.number}}
