


name: Reporting

on:
  workflow_call:
    inputs:
      test:
        description: 'this a test'
        required: false
        default: 'TEST'
        type: string
        
jobs:
  reports:
    if: always()
    timeout-minutes: 10
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Print Type
      run: echo ${{ inputs.test }}

    - name: Print test
      run: echo "Test"

    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci

    - name: Download blob reports from Github actions 
      uses: actions/download-artifact@v3
      with:
        name: all-blob-reports
        path: all-blob-reports

    - name: Merge into HTML report
      run: npx playwright merge-reports --reporter html ./all-blob-reports

    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: html-report-${{ github.run_number	}}
        path: playwright-report
        retention-days: 1
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

